{
 "title": "Titanic API - App Simple Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "API Health Check",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "up{job=\"fastapi_app\"}",
     "legendFormat": "API Status"
    }
   ]
  },
  {
   "title": "Total Predictions Made",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 0 },
   "targets": [
    { "expr": "titanic_predictions_total", "legendFormat": "{Total Predictions Made}" }
   ]
  },
  {
   "title": "Titanic API Outputs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "titanic_predictions_output_total{predicted_class=\"0\"}",
     "legendFormat": "{Not Survived}"
    },
    {
     "expr": "titanic_predictions_output_total{predicted_class=\"1\"}",
     "legendFormat": "{survived}"
    }
   ]
  },
  {
   "title": "Type Of Preditction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "prediction_type_total", "legendFormat": "{{type}}" }
   ]
  }
 ]
}